### ISSUE TITLE
Plugin errors in webpack 2

### ISSUE THREAD

**Issue by brandondoran** [diurnalist/chunk-manifest-webpack-plugin#12]
Because there is a change in Chunk api, this plugin errors with webpack 2. There error is:

``` bash
ERROR in chunk vendor [entry]
app-9148709000831c41a110.js
Chunk.entry was removed. Use hasRuntime()
```

I have a simple fix in a fork. I know webpack 2 is beta but would you accept a PR?

**Comment by kentcdodds** [comment]
@brandondoran could you please open a PR with your fork? It'd be good to get a look at that and discuss fixing/merging :)

**Comment by kentcdodds** [comment]
I opened a PR with your fork @brandondoran.

**Comment by brandondoran** [comment]
@kentcdodds thanks. I wasn't sure the plugin was being maintained so thought I'd just submit an issue first.

**Comment by Ks89** [comment]
I have exactly the same problem.

**Comment by tizmagik** [comment]
Any updates on this?

**Comment by cellis** [comment]
Need this

**Comment by refaelos** [comment]
@kentcdodds do you know when this is going to be merged? I need it as well ...
