### ISSUE TITLE
Using filename as the key in the manifest

### ISSUE THREAD

**Issue by volkanunsal** [diurnalist/chunk-manifest-webpack-plugin#2]
I'm wondering if it would be possible to use the filename instead of a numeric index for the manifest. This would might allow me to require the files by the same canonical name both in development and production.

So, instead of this:
```json
{"1":"Search-d395af9d5105ea5a1e19.js","2":"App-d395af9d5105ea5a1e19.js"}
```

Maybe this?

```json
{"Search.js":"Search-d395af9d5105ea5a1e19.js","App.js":"App-d395af9d5105ea5a1e19.js"}
```

**Comment by diurnalist** [comment]
@volkanunsal sorry for the delay here! Didn't know that anybody was even using this. Not sure what your use case is here. So, you're not using webpack to require the chunks? You're loading them somehow else? The point of using ids was that you would just use webpack as normal, with the bundle-loader or however you're loading async chunks.

**Comment by volkanunsal** [comment]
No worries. I figured this out on my own with a custom plugin.
