### ISSUE TITLE
Supporting non-JS assets

### ISSUE THREAD

**Issue by volkanunsal** [diurnalist/chunk-manifest-webpack-plugin#3]
I've noticed that this plugin doesn't support css and images. Any plans to add support for those asset types?

**Comment by diurnalist** [comment]
Hmm - why do you need this, out of curiosity? The purpose of the module was to make it so if you're doing code-splitting, you can keep the list of all the separate chunks out of the main bundle, for caching reasons. It doesn't change anything about how webpack works. CSS and images are still included as JS modules embedded within some webpack chunk. What are you trying to do?
