### ISSUE TITLE
Add option for path where manifest file should be created

### ISSUE THREAD

**Issue by okonet** [diurnalist/chunk-manifest-webpack-plugin#5]
Right now it's created in `output.path` but my setup requires it in other location. It would be nice to be able to define the path where it should be created and pass it as option.

**Comment by ezekielchentnik** [comment]
you can make the filename relative to the output path, example:

`new ChunkManifestPlugin({filename: './../chunk-manifest.json'})`

`    output: {
        path: path.join(__dirname, '/build/static'),
        publicPath: '/search/',
        filename: hash + '.js',
        chunkFilename: hash + '.js'
    },`

**Comment by okonet** [comment]
Thanks!
